id: D1BD81AA0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-28T05:42:06+00:00'
last_modified: '2022-05-30T04:34:30.338720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f9cb:
      image_group_id: I1PD95942
      title: དུས་གསུམ་བརྟག་པ།
      total_pages: 1198
      order: 97
      base_file: f9cb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
