id: P6518A6ED
initial_creation_type: ocr
source_metadata:
  volumes:
    1d8c69191b4f4ed5bc8411a9fd612a6c:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: དུས་གསུམ་བརྟག་པ།
      total_pages: 1198
      volume_number: 97
